[project]
name = "qenerate"
version = "0.10.0"
requires-python = ">=3.14"
description = "Code Generator for GraphQL Query and Fragment Data Classes"
readme = "README.md"
license = { text = "Apache 2.0" }
authors = [
    { name = "Red Hat - Service Delivery - AppSRE", email = "sd-app-sre@redhat.com" },
]
dependencies = ["graphql-core ~=3.2.5", "requests >=2.32.3"]


[project.urls]
homepage = "https://github.com/app-sre/qenerate"
repository = "https://github.com/app-sre/qenerate"
documentation = "https://github.com/app-sre/qenerate"

[dependency-groups]
dev = [
    "mypy ==2.3.0",
    "pyfakefs ==6.2.0",
    "pytest ==9.1.1",
    "requests-mock ==1.12.1",
    "ruff ==0.16.1",
    "types-requests ==2.33.0.20260712",
]

[project.scripts]
qenerate = 'qenerate.cli:run'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
only-include = ["qenerate"]

[tool.hatch.build.targets.wheel]
only-include = ["qenerate"]

# Ruff configuration
[tool.ruff]
line-length = 88
src = ["qenerate", "tests"]
extend-exclude = [
    # exclude some common cache and tmp directories
    ".local",
    ".cache",
    "tmp",
    "demo",
]
fix = true

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "CPY",     # Missing copyright header
    "undocumented-public-module",    # Missing docstring in public module
    "undocumented-public-class",    # Missing docstring in public class
    "undocumented-public-method",    # Missing docstring in public method
    "undocumented-public-function",    # Missing docstring in public function
    "undocumented-public-package",    # Missing docstring in public package
    "undocumented-magic-method",    # Missing docstring in magic method
    "undocumented-public-init",    # Missing docstring in __init__
    "incorrect-blank-line-before-class",    # 1 blank line required before class docstring
    "blank-line-before-class",    # No blank lines allowed before class docstring
    "multi-line-summary-first-line",    # multi-line-summary-first-line
    "multi-line-summary-second-line",    # multi-line-summary-second-line
    "D4",      # Doc string style
    "line-too-long",    # Line too long
    "logging-f-string",    # Logging statement uses f-string
    "pandas-use-of-dot-values",   # use to_numpy()
    "too-many-public-methods", # Too many public methods
    "too-many-arguments", # Too many arguments
    "too-many-positional-arguments", # Too many positional arguments
    "assert",    # Use of assert detected. Pytest uses assert
    "suspicious-subprocess-import",    # subprocess import
    "raw-string-in-exception",   # Exception must not use a string literal, assign to variable first
    "f-string-in-exception",   # Exception must not use an f-string literal, assign to variable first
    "raise-vanilla-args",  # Avoid specifying long messages outside the exception class
    "try-consider-else",  # try-consider-else
    # pydoclint
    "DOC",
    # May conflict with the formatter, https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "tab-indentation",
    "indentation-with-invalid-multiple",
    "indentation-with-invalid-multiple-comment",
    "over-indented",
    "docstring-tab-indentation",
    "triple-single-quotes",
    "Q",
    "missing-trailing-comma",
    "prohibited-trailing-comma",
    "single-line-implicit-string-concatenation",
    # Change in the future
    "os-path-join", # use pathlib.Path instead of os.path.join
    "TD",     # TODOs
    "line-contains-todo", # TODOs
]
[tool.ruff.format]
preview = true

[tool.ruff.lint.isort]
known-first-party = ["qenerate"]

# Mypy configuration
[tool.mypy]
files = ["qenerate", "tests"]
enable_error_code = ["truthy-bool", "redundant-expr"]
no_implicit_optional = true
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
# Below are all of the packages that don't implement stub packages. Mypy will throw an error if we don't ignore the
# missing imports. See: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
module = ["pytest.*", "pyfakefs.*"]
ignore_missing_imports = true
