"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


DEFINITION = """
query JenkinsConfigs {
  jenkins_configs: jenkins_configs_v1 {
    name
    ...on JenkinsConfig_v1 {
      type
      config_path {
        content
      }
    }
  }
}
"""


class BaseModelWithConfig(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class JenkinsConfigV1(BaseModelWithConfig):
    name: str = Field(..., alias="name")


class ResourceV1(BaseModelWithConfig):
    content: str = Field(..., alias="content")


class JenkinsConfigV1_JenkinsConfigV1(JenkinsConfigV1):
    q_type: str = Field(..., alias="type")
    config_path: Optional[ResourceV1] = Field(..., alias="config_path")


class JenkinsConfigsQueryData(BaseModelWithConfig):
    jenkins_configs: Optional[list[Union[JenkinsConfigV1_JenkinsConfigV1, JenkinsConfigV1]]] = Field(..., alias="jenkins_configs")


def query(query_func: Callable, **kwargs: Any) -> JenkinsConfigsQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        JenkinsConfigsQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return JenkinsConfigsQueryData(**raw_data)
